### ISSUE TITLE
Website doesn't work even after decreasing window width

### ISSUE THREAD

**Issue by thisisommore** [Org-Helping-Hands/react-app#13]
Possible minimum width on windows
![image](https://user-images.githubusercontent.com/51229945/127653393-e135c369-0259-49cb-9093-37a40654d34c.png)

**Comment by m-a-y-a-n-k** [comment]
@thisisommore can I fix this? How do I raise a Pull Request ?

**Comment by thisisommore** [comment]
@m-a-y-a-n-k 
Sure here are steps :-
1. Fork this repo 
2. Then make your changes in it and push
3. Then click on contribute button and there will be option to create pull request
4. After than pull request should be created

Finish till step 2 and then if you have issues further then I will help you

**Comment by m-a-y-a-n-k** [comment]
@thisisommore  check PR link https://github.com/Org-Helping-Hands/react-app/pull/14

**Comment by thisisommore** [comment]
Addressed by #14
